<?php

namespace dokuwiki\plugin\aichat\test;

/**
 * Generic Model Test
 *
 * @group plugin_aichat
 * @group plugins
 * @group internet
 */
class ModelGenericIonosTest extends AbstractModelTest
{
    protected string $provider = 'Generic';
    protected string $api_key_env = 'IONOS_API_KEY';
    protected string $chat_model = 'mistralai/Mistral-Nemo-Instruct-2407';
    protected string $embedding_model = 'BAAI/bge-m3';

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        global $conf;
        $conf['plugin']['aichat']['generic_apiurl'] = 'https://openai.inference.de-txl.ionos.com/v1/';
    }
}
